/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutPostsRouteImport } from './routes/_layout/posts'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as LayoutPublicRouteImport } from './routes/_layout/_public'
import { Route as LayoutProtectedRouteImport } from './routes/_layout/_protected'
import { Route as LayoutPostsIndexRouteImport } from './routes/_layout/posts/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as LayoutPostsPostIdRouteImport } from './routes/_layout/posts/$postId'
import { Route as LayoutPublicSignUpRouteImport } from './routes/_layout/_public/sign-up'
import { Route as LayoutPublicSignInRouteImport } from './routes/_layout/_public/sign-in'
import { Route as LayoutProtectedProtectedRouteImport } from './routes/_layout/_protected/protected'
import { Route as LayoutProtectedDashboardPostsIndexRouteImport } from './routes/_layout/_protected/dashboard/posts/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPostsRoute = LayoutPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPublicRoute = LayoutPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtectedRoute = LayoutProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPostsIndexRoute = LayoutPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPostsRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPostsPostIdRoute = LayoutPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => LayoutPostsRoute,
} as any)
const LayoutPublicSignUpRoute = LayoutPublicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicSignInRoute = LayoutPublicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutProtectedProtectedRoute =
  LayoutProtectedProtectedRouteImport.update({
    id: '/protected',
    path: '/protected',
    getParentRoute: () => LayoutProtectedRoute,
  } as any)
const LayoutProtectedDashboardPostsIndexRoute =
  LayoutProtectedDashboardPostsIndexRouteImport.update({
    id: '/dashboard/posts/',
    path: '/dashboard/posts/',
    getParentRoute: () => LayoutProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof LayoutAboutRoute
  '/posts': typeof LayoutPostsRouteWithChildren
  '/protected': typeof LayoutProtectedProtectedRoute
  '/sign-in': typeof LayoutPublicSignInRoute
  '/sign-up': typeof LayoutPublicSignUpRoute
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/posts/': typeof LayoutPostsIndexRoute
  '/dashboard/posts/': typeof LayoutProtectedDashboardPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof LayoutAboutRoute
  '/protected': typeof LayoutProtectedProtectedRoute
  '/sign-in': typeof LayoutPublicSignInRoute
  '/sign-up': typeof LayoutPublicSignUpRoute
  '/posts/$postId': typeof LayoutPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/posts': typeof LayoutPostsIndexRoute
  '/dashboard/posts': typeof LayoutProtectedDashboardPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_protected': typeof LayoutProtectedRouteWithChildren
  '/_layout/_public': typeof LayoutPublicRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/posts': typeof LayoutPostsRouteWithChildren
  '/_layout/_protected/protected': typeof LayoutProtectedProtectedRoute
  '/_layout/_public/sign-in': typeof LayoutPublicSignInRoute
  '/_layout/_public/sign-up': typeof LayoutPublicSignUpRoute
  '/_layout/posts/$postId': typeof LayoutPostsPostIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_layout/posts/': typeof LayoutPostsIndexRoute
  '/_layout/_protected/dashboard/posts/': typeof LayoutProtectedDashboardPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/posts'
    | '/protected'
    | '/sign-in'
    | '/sign-up'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/posts/'
    | '/dashboard/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/protected'
    | '/sign-in'
    | '/sign-up'
    | '/posts/$postId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/posts'
    | '/dashboard/posts'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/_protected'
    | '/_layout/_public'
    | '/_layout/about'
    | '/_layout/posts'
    | '/_layout/_protected/protected'
    | '/_layout/_public/sign-in'
    | '/_layout/_public/sign-up'
    | '/_layout/posts/$postId'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/_layout/posts/'
    | '/_layout/_protected/dashboard/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/posts': {
      id: '/_layout/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof LayoutPostsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_public': {
      id: '/_layout/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_protected': {
      id: '/_layout/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutProtectedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/posts/': {
      id: '/_layout/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof LayoutPostsIndexRouteImport
      parentRoute: typeof LayoutPostsRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/posts/$postId': {
      id: '/_layout/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof LayoutPostsPostIdRouteImport
      parentRoute: typeof LayoutPostsRoute
    }
    '/_layout/_public/sign-up': {
      id: '/_layout/_public/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof LayoutPublicSignUpRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/sign-in': {
      id: '/_layout/_public/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof LayoutPublicSignInRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_protected/protected': {
      id: '/_layout/_protected/protected'
      path: '/protected'
      fullPath: '/protected'
      preLoaderRoute: typeof LayoutProtectedProtectedRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
    '/_layout/_protected/dashboard/posts/': {
      id: '/_layout/_protected/dashboard/posts/'
      path: '/dashboard/posts'
      fullPath: '/dashboard/posts/'
      preLoaderRoute: typeof LayoutProtectedDashboardPostsIndexRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
  }
}

interface LayoutProtectedRouteChildren {
  LayoutProtectedProtectedRoute: typeof LayoutProtectedProtectedRoute
  LayoutProtectedDashboardPostsIndexRoute: typeof LayoutProtectedDashboardPostsIndexRoute
}

const LayoutProtectedRouteChildren: LayoutProtectedRouteChildren = {
  LayoutProtectedProtectedRoute: LayoutProtectedProtectedRoute,
  LayoutProtectedDashboardPostsIndexRoute:
    LayoutProtectedDashboardPostsIndexRoute,
}

const LayoutProtectedRouteWithChildren = LayoutProtectedRoute._addFileChildren(
  LayoutProtectedRouteChildren,
)

interface LayoutPublicRouteChildren {
  LayoutPublicSignInRoute: typeof LayoutPublicSignInRoute
  LayoutPublicSignUpRoute: typeof LayoutPublicSignUpRoute
}

const LayoutPublicRouteChildren: LayoutPublicRouteChildren = {
  LayoutPublicSignInRoute: LayoutPublicSignInRoute,
  LayoutPublicSignUpRoute: LayoutPublicSignUpRoute,
}

const LayoutPublicRouteWithChildren = LayoutPublicRoute._addFileChildren(
  LayoutPublicRouteChildren,
)

interface LayoutPostsRouteChildren {
  LayoutPostsPostIdRoute: typeof LayoutPostsPostIdRoute
  LayoutPostsIndexRoute: typeof LayoutPostsIndexRoute
}

const LayoutPostsRouteChildren: LayoutPostsRouteChildren = {
  LayoutPostsPostIdRoute: LayoutPostsPostIdRoute,
  LayoutPostsIndexRoute: LayoutPostsIndexRoute,
}

const LayoutPostsRouteWithChildren = LayoutPostsRoute._addFileChildren(
  LayoutPostsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutProtectedRoute: typeof LayoutProtectedRouteWithChildren
  LayoutPublicRoute: typeof LayoutPublicRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutPostsRoute: typeof LayoutPostsRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProtectedRoute: LayoutProtectedRouteWithChildren,
  LayoutPublicRoute: LayoutPublicRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutPostsRoute: LayoutPostsRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
